### ISSUE TITLE
Editeur de formulaires sémantiques - test

### ISSUE THREAD

**Issue by GabarielleGg** [samszo/jardindesconnaissances#1]
Bonjour, en essayant de reproduire l'exemple du tutoriel, lorsque j'ajoute des réponses, il n'y a pas de choix qui s'affichent dans l'interface « Choississez les concepts dans les matrices IEML » . Le background reste noir avec un message « save changed records » qui s'affiche, après vérification, la question est bien enregistrée. S'il-vous-plait, auriez-vous une solution ? Merci d'avance !

**Comment by samszo** [comment]
petit problème d'installation : c'est réglé
